BookListRazor/Controllers/BookController.cs
using BookListRazor.Model;
using BookListRazor.Repositories;
using Microsoft.AspNetCore.Mvc;

namespace BookListRazor.Controllers
{
    [Route("/api/Book")]
    [ApiController]
    public class BookController : Controller
    {
        IBookListRepository<BookListModel> _books;
        public BookController(IBookListRepository<BookListModel> books)
        {
            _books = books;
        }
        [HttpGet]
        public async Task<IActionResult> GetAll()
        {
            return Json(new { data = await _books.GetAsync() });
        }

        [HttpDelete]
        public async Task<IActionResult> Delete(Guid id)
        {
            try
            {
                await _books.DeleteAsync(id);
                return Json(new { success = true, message = "Delete successful" });
            }
            catch (Exception ex)
            {
                return Json(new { success = false, message = ex.Message });
            }
        }
    }
}

BookListRazor/Pages/Create.cshtml.cs
using BookListRazor.Model;
using BookListRazor.Repositories;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace BookListRazor.Pages
{
    public class CreateModel : PageModel
    {
        private readonly IBookListRepository<BookListModel> _books;

        public CreateModel(IBookListRepository<BookListModel> books)
        {
            _books = books;
        }

        [BindProperty]
        public BookListModel Book { get; set; }
        public void OnGet()
        {
        }
        public async Task<IActionResult> OnPost()
        {
            if (ModelState.IsValid)
            {
                await _books.CreateAsync(Book);

                return RedirectToPage("Index");
            }
            else
            {
                return Page();
            }
        }
    }
}

BookListRazor/Pages/Edit.cshtml.cs
using BookListRazor.Model;
using BookListRazor.Repositories;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace BookListRazor.Pages
{
    public class EditModel : PageModel
    {
        private readonly IBookListRepository<BookListModel> _books;

        public EditModel(IBookListRepository<BookListModel> books)
        {
            _books = books;
        }

        [BindProperty]
        public BookListModel Book { get; set; }
        public async Task OnGet(Guid id)
        {
            Book = await _books.GetAsync(id);
        }
        public async Task<IActionResult> OnPost(Guid id)
        {
            if (ModelState.IsValid)
            {
                await _books.UpdateAsync(id, Book);

                return RedirectToPage("Index");
            }
            else
            {
                return Page();
            }
        }
    }
}

BookListRazor/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace BookListRazor.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

BookListRazor/Pages/Index.cshtml.cs
using BookListRazor.Model;
using BookListRazor.Repositories;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace BookListRazor.Pages
{
    public class IndexModel : PageModel
    {
        private readonly IBookListRepository<BookListModel> _books;

        public IndexModel(IBookListRepository<BookListModel> books)
        {
            _books = books;
        }

        public List<BookListModel> Books { get; set; }
        public async Task OnGet()
        {
            Books = await _books.GetAsync();
        }

        public async Task<IActionResult> OnPostDelete(Guid id)
        {
            await _books.DeleteAsync(id);

            return RedirectToPage("Index");
        }
    }
}

BookListRazor/Pages/Upsert.cshtml.cs
using BookListRazor.Model;
using BookListRazor.Repositories;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace BookListRazor.Pages
{
    public class UpsertModel : PageModel
    {
        private readonly IBookListRepository<BookListModel> _books;

        public UpsertModel(IBookListRepository<BookListModel> books)
        {
            _books = books;
        }

        [BindProperty]
        public BookListModel Book { get; set; }
        public async Task OnGet(string id)
        {
            if (id == null)
            {
                Book = new BookListModel();
            }
            else
            {
                Book = await _books.GetAsync(new Guid(id));
            }
        }
        public async Task<IActionResult> OnPost(string id)
        {
            if (ModelState.IsValid)
            {
                if (id == null)
                {
                    await _books.CreateAsync(Book);
                }
                else
                {
                    await _books.UpdateAsync(new Guid(id), Book);
                }
                return RedirectToPage("Index");
            }
            else
            {
                return Page();
            }
        }
    }
}

BookListRazor/Pages/Create.cshtml
@page
@model BookListRazor.Pages.CreateModel
@{
}

<h2 class="text-info">Create New Book</h2>
<br />

<div class="border container" style="padding:30px;">
    <form method="post">
        <div class="text-danger" asp-validation-summary="ModelOnly"></div>
        <div class="form-group my-3 row">
            <div class="col-3">
                <label asp-for="Book.Name"></label>
            </div>
            <div class="col-6">
                <input asp-for="Book.Name" class="form-control" />
                <span asp-validation-for="Book.Name" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group my-3 row">
            <div class="col-3">
                <label asp-for="Book.Author"></label>
            </div>
            <div class="col-6">
                <input asp-for="Book.Author" class="form-control" />
                <span asp-validation-for="Book.Author" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group my-3 row">
            <div class="col-3">
                <label asp-for="Book.ISBN"></label>
            </div>
            <div class="col-6">
                <input asp-for="Book.ISBN" class="form-control" />
                <span asp-validation-for="Book.ISBN" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group my-3 row">
            <div class="col-3 offset-3">
                <input type="submit" value="Create" class="btn btn-primary form-control" />
            </div>
            <div class="col-3">
                <a asp-page="Index" class="btn btn-success form-control">Back to List</a>
            </div>
        </div>
    </form>
</div>

@section Scripts
{
    <partial name="_ValidationScriptsPartial" />
}

BookListRazor/Pages/Edit.cshtml
@page
@model BookListRazor.Pages.EditModel
@{
}

<h2 class="text-info">Edit New Book</h2>
<br />

<div class="border container" style="padding:30px;">
    <form method="post">
        <div class="text-danger" asp-validation-summary="ModelOnly"></div>
        <div class="form-group my-3 row">
            <div class="col-3">
                <label asp-for="Book.Name"></label>
            </div>
            <div class="col-6">
                <input asp-for="Book.Name" class="form-control" />
                <span asp-validation-for="Book.Name" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group my-3 row">
            <div class="col-3">
                <label asp-for="Book.Author"></label>
            </div>
            <div class="col-6">
                <input asp-for="Book.Author" class="form-control" />
                <span asp-validation-for="Book.Author" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group my-3 row">
            <div class="col-3">
                <label asp-for="Book.ISBN"></label>
            </div>
            <div class="col-6">
                <input asp-for="Book.ISBN" class="form-control" />
                <span asp-validation-for="Book.ISBN" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group my-3 row">
            <div class="col-3 offset-3">
                <input type="submit" value="Update" class="btn btn-primary form-control" />
            </div>
            <div class="col-3">
                <a asp-page="Index" class="btn btn-success form-control">Back to List</a>
            </div>
        </div>
    </form>
</div>

@section Scripts
{
    <partial name="_ValidationScriptsPartial" />
}

BookListRazor/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="container row p-0 m-0">
    <div class="col-6">
        <h2 class="text-info">Book List</h2>
    </div>
    <div class="col-3">
        <a asp-page="Create" class="btn btn-info form-control text-white">Create New Book</a>
    </div>
    <div class="col-3">
        <a asp-page="Upsert" class="btn btn-info form-control text-white">Upsert New Book</a>
    </div>

    <div class="col-12 border p-3 mt-3">
        <form method="post">
            @if (Model.Books.Count > 0)
            {
                <table class="table table-striped border">
                    <tr class="table-secondary">
                        <th class="w-25">
                            <label asp-for="Books.FirstOrDefault().Name"></label>
                        </th>
                        <th class="w-25">
                            <label asp-for="Books.FirstOrDefault().Author"></label>
                        </th>
                        <th class="w-25">
                            <label asp-for="Books.FirstOrDefault().ISBN"></label>
                        </th>
                        <th class="w-25">
                            <label>Action</label>
                        </th>
                    </tr>
                    @foreach (var item in Model.Books)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(m => item.Name)
                            </td>
                            <td>
                                @Html.DisplayFor(m => item.Author)
                            </td>
                            <td>
                                @Html.DisplayFor(m => item.ISBN)
                            </td>
                            <td>
                                <button asp-page-handler="Delete" asp-route-id="@item.Id"
                            onclick="return confirm('Are you sure you want to delete?')"
                            class="btn btn-danger me-2">Delete</button>

                                <a asp-page="Edit" asp-route-id="@item.Id" class="btn btn-success text-white px-4">Edit</a>
                            </td>
                        </tr>
                    }
                </table>
            }
            else
            {
                <p>No books available.</p>
            }
        </form>
    </div>

    <div class="col-12" style="text-align:center">
        <br />
        <span class="h3 text-info">OR</span>
        <br /><br />
    </div>
    <div class="col-12 border p-3">
        <table id="DT_load" class="table table-striped table-bordered" style="width:100%">
            <thead>
                <tr>
                    <th> Name </th>
                    <th> Author</th>
                    <th> ISBN</th>
                    <th> Action </th>
                </tr>
            </thead>
        </table>
    </div>
</div>

@section Scripts{ 
    <script src="~/js/bookList.js"></script>
}

BookListRazor/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BookListRazor</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BookListRazor.styles.css" asp-append-version="true" />

    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">BookList</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        <br />
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - BookList - <a href="https://rajangautam.com.np">Rajan Gautam</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    <script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

BookListRazor/Pages/Upsert.cshtml
@page
@model BookListRazor.Pages.UpsertModel

<h2 class="text-info">@(Model.Book.Id != Guid.Empty ? "Edit" : "Create") New Book</h2>
<br />

<div class="border container" style="padding:30px;">
    <form method="post">
        <div class="text-danger" asp-validation-summary="ModelOnly"></div>
        <div class="form-group my-3 row">
            <div class="col-3">
                <label asp-for="Book.Name"></label>
            </div>
            <div class="col-6">
                <input asp-for="Book.Name" class="form-control" />
                <span asp-validation-for="Book.Name" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group my-3 row">
            <div class="col-3">
                <label asp-for="Book.Author"></label>
            </div>
            <div class="col-6">
                <input asp-for="Book.Author" class="form-control" />
                <span asp-validation-for="Book.Author" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group my-3 row">
            <div class="col-3">
                <label asp-for="Book.ISBN"></label>
            </div>
            <div class="col-6">
                <input asp-for="Book.ISBN" class="form-control" />
                <span asp-validation-for="Book.ISBN" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group my-3 row">
            <div class="col-3 offset-3">
                <button type="submit" class="btn btn-primary form-control">
                    @(Model.Book.Id != Guid.Empty ? "Edit" : "Create")
                </button>
            </div>
            <div class="col-3">
                <a asp-page="Index" class="btn btn-success form-control">Back to List</a>
            </div>
        </div>
    </form>
</div>

@section Scripts
{
    <partial name="_ValidationScriptsPartial" />
}